name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependecies 
        run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      - name: Run Tests
      run: |
        python test.py 
